# Generated by Django 5.2.7 on 2026-01-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(help_text='ID da atividade no Strava', unique=True)),
                ('name', models.CharField(help_text='Nome da atividade', max_length=255)),
                ('distance', models.FloatField(help_text='Distância em metros')),
                ('moving_time', models.PositiveIntegerField(help_text='Tempo em movimento (segundos)')),
                ('sport_type', models.CharField(help_text='Tipo de esporte (Run, Walk, Ride, etc)', max_length=50)),
                ('start_date', models.DateTimeField(help_text='Data/hora de início (UTC)')),
                ('average_speed', models.FloatField(blank=True, help_text='Velocidade média (m/s)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-start_date'],
            },
        ),
    ]
